### ISSUE TITLE
st: String or setTimeout?

### ISSUE THREAD

**Issue by gmillward** [extrabacon/atom-turbo-javascript#2]
Hey extrabacon,

Thanks for the great package! It looks like "st" is overloaded for String and setTimeout (I'm getting "String" in Atom). Is there a way to trigger different behavior, or should there be a separate snippet for each one? (Tip: search for "st:" in README.md).

Thanks,
Greg

**Comment by extrabacon** [comment]
This is fixed in 1.0.0.
