### ISSUE TITLE
Arrow functions for BDD Suite

### ISSUE THREAD

**Issue by dacodekid** [extrabacon/atom-turbo-javascript#25]
Would it be possible to add this support?

**Comment by dacodekid** [comment]
Just incase if you are interested - plz take a look at my PR https://github.com/extrabacon/atom-turbo-javascript/pull/26.  Have tested it and works fine.

**Comment by extrabacon** [comment]
That is a lot of redundant snippets. Arrow functions do not add much here, except for consistency. We should consider updating existing snippets instead.

I also know that many users do not yet run their tests with an engine supporting arrow functions, even though the tested code is (source is transpiled with Babel, but tests still run with regular Node).

**Comment by dacodekid** [comment]
Agree.  It make sense to move these snippets to my atom's snippets.

**Comment by extrabacon** [comment]
I reconsidered by position, I think we do need arrow functions in our BDD snippets. It's cleaner and provides better consistency. Babel has excellent support for all test tools, so there should be no reason not to use them.

**Comment by extrabacon** [comment]
Published in version 1.2.0.
