### ISSUE TITLE
Double and single quotes consistency

### ISSUE THREAD

**Issue by tjoskar** [extrabacon/atom-turbo-javascript#28]
Hi,

It seems to be single quotes for all snippets except for the `bdd`-snippets (https://github.com/extrabacon/atom-turbo-javascript/blob/master/snippets/bdd.cson#L5). I believe that the snippets for `bdd` should be updated to use single quotes. 

This will affect #26.

**Comment by jasondonnette** [comment]
Seconded, and even better it would be great to have a setting to chose between single and double quotes.

**Comment by extrabacon** [comment]
Published in version 1.2.0.
