### ISSUE TITLE
Wrapping in braces is broken

### ISSUE THREAD

**Issue by anisylen** [extrabacon/atom-turbo-javascript#29]
Apparently the plugin actually does wrap the selected code in braces but then does some stuff extra that unindents the code and removes the opening brace. Doing a couple of "undo" actions takes the code back to where it was properly wrapped in braces.

**Comment by extrabacon** [comment]
Yes, it is definitely not perfect. Do you have a snippet I can use to test?

**Comment by anisylen** [comment]
Here's what happens in a step-by-step process:

Here's a bit of code:

`var a = b;`

Here's what happens after pressing `Ctrl+B`

`var a = b;`

That's it. You may think nothing happened but here's what happens each time I press `Command+Z`:

`var a = b;`
Mind you, this is AFTER I press Undo meaning the text stays the same but is now selected if it wasn't before and stays selected if it was.

```javascript
{
    var a = b;
}
```

```
{
var a = b;
}
```

`var a = b;`

At this point, the next undo undoes whatever I did before I pressed `Ctrl + B`. BTW, the first line

**Comment by anisylen** [comment]
Heyoo this is no longer an issue. Wrapping in braces works as expected. Thanks a bunch!
