### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by ericclemmons** [extrabacon/atom-turbo-javascript#6]
Just installed Atom @ Version 0.187.0 (0.187.0) and installed this project.  Attempted a `CTRL+;` & got:

> atom.workspaceView is no longer available.
> In most cases you will not need the view. See the Workspace docs for
> alternatives: https://atom.io/docs/api/latest/Workspace.
> If you do need the view, please use `atom.views.getView(atom.workspace)`,
> which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Applications/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Object.activate (/Users/Eric/.atom/packages/turbo-javascript/lib/turbo-javascript.coffee:3:9)
```

**Comment by extrabacon** [comment]
Fixed!

**Comment by ericclemmons** [comment]
<3 youuuuu! Thanks!
