### ISSUE TITLE
ES6 snippets?

### ISSUE THREAD

**Issue by Chrisui** [extrabacon/atom-turbo-javascript#7]
Would you be open to the implementation some snippets for ES6 since the last RC is now TC39 accepted and it's used *fully* through traspilers such as Babel? 

Lot's of new syntax so would be nice to have some qucik snippets!

I would be more than happy to work on a PR for this. :)

**Comment by extrabacon** [comment]
Of course! It's a shame I haven't looked into ES6 yet... PRs are welcome!

**Comment by extrabacon** [comment]
I think the inclusion the ES6 is a great opportunity to revisit existing snippets for maximum productivity (let's keep it turbo).

- Remove semi-colons from snippets, for those who prefer it this way. Those still in favor of semi-colons are already used to add them everywhere right? See https://twitter.com/andrewtjoslin/status/578213277496266752
- Remove snippets for types (string, number, etc) and other things already showing up in Atom auto-complete
- Chainable snippets should always use arrow functions

Suggestions?

**Comment by luisrudge** [comment]
I only disagree with no semicolons. But I'm all in with arrow functions and removing types

**Comment by extrabacon** [comment]
Heh, I'm using semi-colons myself right now. Been using semi-colons forever... But is it slowing us down?

**Comment by luisrudge** [comment]
I guess not, but I'm pretty sure the vast majority of people are using semicollons

**Comment by extrabacon** [comment]
Version 1.0.0 is up with ES6-ready snippets.

**Comment by luisrudge** [comment]
awesome!
